### ISSUE TITLE
Not working on AMD GPU

### ISSUE THREAD

**Issue by szdytom** [dianariyanto/virtual-display-linux#10]
nothing happend after reboot.
Does anyone has any idea?

**Comment by Tecnoll** [comment]
> nothing happend after reboot.
> Does anyone has any idea?

Man i have the some issue, it's  don't work!

**Comment by a-almallah** [comment]
for me X11 gave me an error and didn't start, I'm using this on Manjaro.

**Comment by NoXXoN123** [comment]
IT Just broke my graphic config. Linux Said
[FAILED] Failed to start Light Display Manager.

**Comment by dianariyanto** [comment]
#16
