### ISSUE TITLE
Not working on pop os 21.04??

### ISSUE THREAD

**Issue by sudo455** [dianariyanto/virtual-display-linux#11]
i get this result wean i run the script

Start configuration
xrandr: cannot find mode "1920x1200"
add resolution 1920x1200
xrandr: cannot find mode 1920x1200
start display VIRTUAL1 to 1920x1200
Screen 0: minimum 8 x 8, current 1366 x 768, maximum 32767 x 32767
eDP1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 340mm x 190mm
   1366x768      59.97*+
   1360x768      59.96  
   1280x720      59.74  
   1024x768      60.00  
   1024x576      60.00    59.90    59.82  
   960x540       60.00    59.63    59.82  
   800x600       60.32    56.25  
   864x486       60.00    59.92    59.57  
   640x480       59.94  
   720x405       59.51    60.00    58.99  
   680x384       60.00  
   640x360       59.84    59.32    60.00  
DP1 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
VGA1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
VIRTUAL2 disconnected (normal left inverted right x axis y axis)
  1920x1200_60.00 (0x16d) 193.160MHz -HSync +VSync
        h: width  1920 start 2048 end 2256 total 2592 skew    0 clock  74.52KHz
        v: height 1200 start 1201 end 1204 total 1242           clock  60.00Hz

Done, Check your VDL Monitor on System Setting > Display

i tried to modify it (because it wasn't working) in the line 6 and writing
      xrandr --newmode "1920x1200_60.00"  193.16  1920 2048 2256 2592  1200 1201 1204 1242  -HSync +Vsync

and in the line 11 by replace  LVDS1 to eDP1 didn't work ether and i change it again exactly as it was before i made the changes
What do i do to make it work or to delete the virtual displays?

**Comment by dianariyanto** [comment]
This script only works on Intel CPUs with integrated graphics only for now. 
If your device using another graphic card, you cant use this script. 
Or, if you using Nvidia you can read this #9

**Comment by Eris7090** [comment]
I know this is closed but I am also on Pop_OS! 21.04 and I am having an issue.

Hardware: Thinkpad T530 
CPU: Intel i5-3320M
GPU: Integrated graphics, Intel 3rd Gen Core processor Graphics Controller, Intel® HD Graphics 4000 (IVB GT2). Same thing but labeled different in every menu so I wasn't sure which one was best.

I have Remmina installed and I followed the quick set up but every time I try to run ./vdl-monitor I get 

`cp: cannot create regular file '/usr/share/X11/xorg.conf.d/20-intel.conf': Permission denied
[vdl-monitor] You must reboot or relogin current session to finish setup
`

At first I though "I was warned about this" so I rebooted and tried again but I still get the same thing. So I tried logging out and logging back in but I still get the same thing. Any help would be appreciated.

**Comment by Eris7090** [comment]
Wait am I just retarded and I have to cp it myself?

**Comment by Eris7090** [comment]
okay it works now I'm just retarded. I had to cp it myself. Now i just need to figure out how to connect to it. I've never used vnc before

**Comment by KaKi87** [comment]
> I'm just retarded

No you're not, I encountered the same issue and yes indeed copying the file manually does make the error disappear, but the error shouldn't have been there in the first place, as the README doesn't say anything about copying this file.
