### ISSUE TITLE
Glitch when create a 20-intel.conf file in X11 folder

### ISSUE THREAD

**Issue by ElderTugBoat786** [dianariyanto/virtual-display-linux#2]
Hello,

I tried to use this project and right after the first run and next reboot it creates the virtual monitors correctly but strange glitches appear on the screen

![20-intel conf glitch](https://user-images.githubusercontent.com/38555796/95193398-0dbec780-07d4-11eb-9edf-fb8306354fbc.png)

I can't understand what the problem is

Some info

`uname -a
Linux pop-os 5.4.0-7642-generic #46~1598628707~20.04~040157c-Ubuntu SMP Fri Aug 28 18:02:16 UTC  x86_64 x86_64 x86_64 GNU/Linux
`
`Graphic Card Intel Corporation UHD Graphics 630 (Mobile)`

Any suggestion?

**Comment by dianariyanto** [comment]
I think it's related to your version of the graphics card or something. I'm sorry if this doesn't work well on your device. May I know the type of device you are using?

I think it will only work if the device is using _xorg_. 
Hope that you have a better solution.

Source : [here](https://unix.stackexchange.com/questions/378373/add-virtual-output-to-xorg)

**Comment by ElderTugBoat786** [comment]
Thanks for the response, 

i use a Dell XPS 15 7590. i suppose that could be a compatiby problem about graphics card, os and hardware.
I have checked and I use xorg.
I'll do more research

Thanks
