### ISSUE TITLE
Provided 20-intel.conf kills my X

### ISSUE THREAD

**Issue by Hebgbs** [dianariyanto/virtual-display-linux#20]
`$ cat /etc/*-release`
```
Manjaro Linux
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.0
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"
Manjaro Linux
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```
`$ inxi -G`
```
  Device-1: AMD Picasso driver: amdgpu v: kernel
  Device-2: IMC Networks Integrated Camera type: USB driver: uvcvideo
  Display: x11 server: X.Org 1.21.1.2 driver: loaded: amdgpu,ati
    unloaded: modesetting resolution: 1440x810~60Hz
  OpenGL: renderer: AMD Radeon Vega 8 Graphics (RAVEN DRM 3.42.0
    5.15.7-1-MANJARO LLVM 13.0.0)
    v: 4.6 Mesa 21.2.5
```

Could my problem be that I am unable to use your repository because of having an AMD iGPU rather than an Intel iGPU?

**Comment by pinkpigeonltd** [comment]
This script is indeed only compatible with intel integrated graphics.

Interestingly, it also kills my X. On Linux Mint with Intel integrated graphics here.

**Comment by Hebgbs** [comment]
@pinkpigeonltd just curious, does it completely overwrite or append to existing `20-intel.conf`?

**Comment by pinkpigeonltd** [comment]
Ah, that might be a hint as to why this is going wrong.
It would appear that this is an overwrite, not an append.

I have found out meanwhile, that using ```xrandr``` I can see VIRTUAL1, however, it is marked as 'disconnected'. 

So I tried adding a mode by using ```xrandr --addmode VIRTUAL1 1920x1080``` and then ```xrandr --output VIRTUAL1 --mode 1920x1080 --right-of eDP1``

But this just corrupts my screen and crashes Cinnamon.

**Comment by revilofr** [comment]
Hi, I follow up a thread I saw somewhere. Stupidly I didn't check compatibility before, now I crashed my x. is there a way to properly remove virtual display and have my x work fine again ?

thanks

**Comment by revilofr** [comment]
For those that are on the same situation, pretty much straight forward:

- I have to remove ```20-intel.conf``` (located in ```/usr/share/X11/xorg.conf.d/```)
- And finally remove the git local directory ```<The path where you git cloned>/virtual-display/linux```

**Comment by bekopharm** [comment]
> Interestingly, it also kills my X. On Linux Mint with Intel integrated graphics here.

this is probably because it was the _only_ remaining hardcoded device driver at this point. If none is provided X is smart and detects some. If one is provided autoconf may fail. Try again with something like this:

```
Section "Device"
       Identifier "amdgpu0"
       Driver "amdgpu"
Endsection

Section "Device"
       Identifier "IntelVirtual0"
       Driver     "intel"
       Option     "VirtualHeads" "1" 
EndSection
```

Wrote in great detail about this approach at https://beko.famkos.net/2021/05/31/extreme-multihead-for-gaming-on-linux-pc/
