### ISSUE TITLE
Black screen after running

### ISSUE THREAD

**Issue by administratornathen** [dianariyanto/virtual-display-linux#24]
hello，What can be done to fix it? 
The system is  CentOS Linux release 7.9.2009       3.10.0-1160.el7.x86_64
The resolution I set is 1024*768
![微信截图_20220531150227](https://user-images.githubusercontent.com/106583954/171127407-b4761010-b5b1-4625-ae5e-d6ac35c0423e.png)

**Comment by dianariyanto** [comment]
This instruction #16  might be useful for you to fix this problem
