### ISSUE TITLE
Black screen on every linux boot

### ISSUE THREAD

**Issue by cosimonegri** [dianariyanto/virtual-display-linux#25]
I'm using Ubuntu 20.04.4 LTS on an HP 15s laptop, and my graphic card is an Interl UHD 620.

I'm a newbie who is transitioning from Windows to linux,

After the last command i got this (which I think is an error):
![terminal](https://user-images.githubusercontent.com/93294521/172147152-84dd573f-e32b-4ac9-ad86-29eda86a8bd0.jpeg)

But the real problem is that now, at every boot, i have a black screen. 
Now my pc works only with the Linux recovery mode (except from something like screen brightness change, that is always broken)

How can i solve the problem?

**Comment by dianariyanto** [comment]
#16

**Comment by dianariyanto** [comment]
#16
