### ISSUE TITLE
Request for source code of vdl-monitor binary file in this repo

### ISSUE THREAD

**Issue by vishal733** [dianariyanto/virtual-display-linux#4]
Is it possible to share source code of vdl-monitor binary file?
That will give a clear idea on what changes it is bringing to the system, and would make it easy to revert them back later on.

**Comment by dianariyanto** [comment]
Hi @vishal733 , 
All file you need is allready available on this repo. you can fork this source to make your own custom script. it just regular bash script to manage xrandr.
