### ISSUE TITLE
Caused a system failure on Ubuntu 20.04

### ISSUE THREAD

**Issue by vishal733** [dianariyanto/virtual-display-linux#5]
I installed it on Ubuntu 20.04.
And after system reboot, the system isn't working.

Since this machine is remotely located, I don't have further details on what broke.

That machine also has a dedicated NVIDIA GPU. Not sure if it's related to that..
I don't even have details on how to revert the changes that your script made to the remote system.

**Comment by bocklucas** [comment]
Think this is related to https://github.com/dianariyanto/virtual-display-linux/issues/9, have to delete the file `/usr/share/X11/xorg.conf.d/20-intel`
