### ISSUE TITLE
Does it need to have TeamViewer open on two devices?

### ISSUE THREAD

**Issue by a0m0rajab** [dianariyanto/virtual-display-linux#6]
It was not clear on the docs though, thought to ask :)

**Comment by dianariyanto** [comment]
> It was not clear on the docs though, thought to ask :)

The Readme.md said

Install teamviewer on both devices. (You also can use VNC to)

that mean, yes. you must install and connect both devices using teamviewer or vnc. Laptop as server and the another device as client. @a0m0rajab
