### ISSUE TITLE
How to Undo Changes

### ISSUE THREAD

**Issue by MaximoMachado** [dianariyanto/virtual-display-linux#7]
I ran the script and immediately my computer started hitching in the terminal and weird artifacts appeared on my desktop icons and backgrounds.

How do I revert the changes that the script made?

**Comment by dianariyanto** [comment]
> I ran the script and immediately my computer started hitching in the terminal and weird artifacts appeared on my desktop icons and backgrounds.
> 
> How do I revert the changes that the script made?

reboot can revert back xrandr config to default. no need to do something else. its just a portable bash script. @MaximoMachado

**Comment by dianariyanto** [comment]
> I ran the script and immediately my computer started hitching in the terminal and weird artifacts appeared on my desktop icons and backgrounds.
> 
> How do I revert the changes that the script made?

reboot can revert back xrandr config to default. no need to do something else. its just a portable bash script. @MaximoMachado

**Comment by MaximoMachado** [comment]
Sounds good, thank you!
