### ISSUE TITLE
How do you delete the virtual display?

### ISSUE THREAD

**Issue by aaylnx** [dianariyanto/virtual-display-linux#8]
This is a great project. I have been using it with Deskreen on linux.

https://deskreen.com/

When you want do turn it off, how do you do that?  

Thanks!

**Comment by pmosko** [comment]
> This is a great project. I have been using it with Deskreen on linux.
> 
> https://deskreen.com/
> 
> When you want do turn it off, how do you do that?
> 
> Thanks!

I found that you can simply turn off display in the display settings. If you want more permanent solution then remove /usr/share/X11/xorg.conf.d/20-intel.conf and reboot.

**Comment by dianariyanto** [comment]
@aaylnx reboot or re-login current session can revert virtual display configuration.
Duplicate of #7

**Comment by lucasghelal** [comment]
> > This is a great project. I have been using it with Deskreen on linux.
> > https://deskreen.com/
> > When you want do turn it off, how do you do that?
> > Thanks!
> 
> I found that you can simply turn off display in the display settings. If you want more permanent solution then remove /usr/share/X11/xorg.conf.d/20-intel.conf and reboot.

remove this fine works fine for me too :)
